// Code generated by "stringer -type ObjectType"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ObjectTypeNumber-1]
	_ = x[ObjectTypeString-2]
	_ = x[ObjectTypeSymbol-3]
}

const _ObjectType_name = "ObjectTypeNumberObjectTypeStringObjectTypeSymbol"

var _ObjectType_index = [...]uint8{0, 16, 32, 48}

func (i ObjectType) String() string {
	i -= 1
	if i < 0 || i >= ObjectType(len(_ObjectType_index)-1) {
		return "ObjectType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _ObjectType_name[_ObjectType_index[i]:_ObjectType_index[i+1]]
}
