// Code generated by "stringer -type symbolType"; DO NOT EDIT.

package object

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[SymbolTypeValue-1]
	_ = x[SymbolTypeFilter-2]
	_ = x[SymbolTypeFnValue-3]
	_ = x[SymbolTypeFunction-4]
}

const _symbolType_name = "SymbolTypeValueSymbolTypeFilterSymbolTypeFnValueSymbolTypeFunction"

var _symbolType_index = [...]uint8{0, 15, 31, 48, 66}

func (i symbolType) String() string {
	i -= 1
	if i < 0 || i >= symbolType(len(_symbolType_index)-1) {
		return "symbolType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _symbolType_name[_symbolType_index[i]:_symbolType_index[i+1]]
}
