// Code generated by "stringer -type TokenType"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[TokenTypeError-0]
	_ = x[TokenTypeDot-1]
	_ = x[TokenTypeEOF-2]
	_ = x[TokenTypeText-3]
	_ = x[TokenTypeIdentifier-4]
	_ = x[TokenTypeNumber-5]
	_ = x[TokenTypeString-6]
	_ = x[TokenTypeLMeta-7]
	_ = x[TokenTypeRMeta-8]
	_ = x[TokenTypeLParen-9]
	_ = x[TokenTypeRParen-10]
	_ = x[TokenTypePipe-11]
}

const _TokenType_name = "TokenTypeErrorTokenTypeDotTokenTypeEOFTokenTypeTextTokenTypeIdentifierTokenTypeNumberTokenTypeStringTokenTypeLMetaTokenTypeRMetaTokenTypeLParenTokenTypeRParenTokenTypePipe"

var _TokenType_index = [...]uint8{0, 14, 26, 38, 51, 70, 85, 100, 114, 128, 143, 158, 171}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
